version assert implementation with rect select test

diff --git a/run b/run
--- a/run
+++ b/run
@@ -92,7 +92,7 @@ sel_sid=$(curl -s -X POST -H "Content-Type: application/json; charset=utf-8" \
     "firstMatch": [{}]
   }
 }
-' http://localhost:4444/session | jq -r '.value.sessionId')
+' http://localhost:4444/session 2>/dev/null | jq -r '.value.sessionId')
 unset sel_log_file sel_chromedriver
 sleep 1
 
@@ -101,7 +101,7 @@ curl -s -X POST -H "Content-Type: application/json; charset=utf-8" \
         "width": 1600,
         "height": 1000
       }' \
-  http://localhost:4444/session/${sel_sid}/window/rect
+  http://localhost:4444/session/${sel_sid}/window/rect 2>/dev/null 1>&2
 
 sleep 1
 
@@ -112,13 +112,13 @@ sleep 1
 version_ordinal=-1
 version_index=index.html
 
-while IFS=',' read -r harness giturl gittag index ordinal; do
+while IFS=',' read -r harness giturl gittag index version ordinal; do
     if [[ "$giturl" == "giturl" ]]; then
         continue
     fi
     gitname=$(echo "$giturl" | cut -d '/' -f2)
     echo "${gitname} ${giturl} ${gittag}"
-    if [[ "$gittag" == "$ft_version"  && "$ft_harness" == "$harness" ]]; then
+    if [[ "$version" == "$ft_version"  && "$ft_harness" == "$harness" ]]; then
         version_ordinal="$ordinal"
         version_index="$index"
         break
@@ -141,24 +141,24 @@ if [[ $ft_snap -eq 0 ]]; then
     if [[ -d "./sut" ]]; then
         rm -rf "./sut"
     fi
-    result_file="./results.${version_ordinal}"
-    if [[ -f "$result_file" ]]; then
-        rm "$result_file"
-    fi
+    # result_file="./results.${version_ordinal}"
+    # if [[ -f "$result_file" ]]; then
+    #     rm "$result_file"
+    # fi
     gitname=$(echo "$giturl" | cut -d '/' -f2)
-    GIT_SSH_COMMAND="${GIT_SSH}" git clone "git@github.com:${giturl}.git" sut || {
+    GIT_SSH_COMMAND="${GIT_SSH}" git clone "git@github.com:${giturl}.git" sut 1>/dev/null 2>&1 || {
         echo "Error: Failed to clone repository: ${giturl}" 1>&2
         exit 1
     }
-    (cd sut && GIT_SSH_COMMAND="${GIT_SSH}" git checkout "$gittag") || {
+    (cd sut && GIT_SSH_COMMAND="${GIT_SSH}" git checkout "$gittag" 1>/dev/null 2>/dev/null) || {
         echo "Error: Failed to checkout tag '$gittag' in repository '${giturl}'." 1>&2
         exit 1
     }
     echo "$version_ordinal" > "./sut.version"  # readable by tests
 
     # run tests
-    echo "test ${version_index}. ${PWD}"
-    ft_index=${version_index}
+    # echo "test ${version_index}. ${PWD}"
+    ft_index=${index}
     for t in ${src_dir}/act.svg/tests/test*
     do
         if [[ "$t" =~ '~' ]]; then
@@ -168,25 +168,28 @@ if [[ $ft_snap -eq 0 ]]; then
     done
     . ns delete ft_index
     # res=$(npx nightwatch --env="chrome" --src=tests --git-tag="$ft_version" --index="${version_index}")
-    echo "$res"
-    passed=$(echo "$res" | grep -oP "Tests passed: \K\d+" || echo "0")
-    failed=$(echo "$res" | grep -oP "Tests failed: \K\d+" || echo "0")
-    errors=$(echo "$res" | grep -oP "Errors: \K\d+" || echo "0")
-    skipped=$(echo "$res" | grep -oP "Skipped: \K\d+" || echo "0")
-    # defaults
-    : ${passed:=0}
-    : ${failed:=0}
-    : ${errors:=0}
-    : ${skipped:=0}
+    # echo "$res"
+    # passed=$(echo "$res" | grep -oP "Tests passed: \K\d+" || echo "0")
+    # failed=$(echo "$res" | grep -oP "Tests failed: \K\d+" || echo "0")
+    # errors=$(echo "$res" | grep -oP "Errors: \K\d+" || echo "0")
+    # skipped=$(echo "$res" | grep -oP "Skipped: \K\d+" || echo "0")
+    # # defaults
+    # : ${passed:=0}
+    # : ${failed:=0}
+    # : ${errors:=0}
+    # : ${skipped:=0}
 
-    echo "${ft_version},$passed,$failed,$errors,$skipped" >> "$result_file"
+    # echo "${ft_version},$passed,$failed,$errors,$skipped" >> "$result_file"
+    read -p "Test run has ended. Press enter to quit the session..." _
+    curl -s -X DELETE http://localhost:4444/session/${sel_sid} 1>/dev/null 2>/dev/null
+    sleep 1
     exit 0
 fi
 
 unset giturl gittag
 
 # SNAPSHOT MODE -- RUN EACH SNAPSHOT
-while IFS=',' read -r harness giturl gittag index ordinal; do
+while IFS=',' read -r harness giturl gittag index version ordinal; do
 
     if [[ "$giturl" == "giturl" ]]; then
         continue
@@ -196,42 +199,53 @@ while IFS=',' read -r harness giturl gittag index ordinal; do
     if [[ -d "./sut" ]]; then
         rm -rf "./sut"
     fi
-    result_file="./results.${ordinal}"
-    if [[ -f "$result_file" ]]; then
-        rm "$result_file"
-    fi
+    # result_file="./results.${ordinal}"
+    # if [[ -f "$result_file" ]]; then
+    #     rm "$result_file"
+    # fi
 
     gitname=$(echo "$giturl" | cut -d '/' -f2)
 
-    GIT_SSH_COMMAND="${GIT_SSH}" git clone "git@github.com:${giturl}.git" sut || {
+    GIT_SSH_COMMAND="${GIT_SSH}" git clone "git@github.com:${giturl}.git" sut 1>/dev/null 2>&1 || {
         echo "Error: Failed to clone repository: ${giturl}" 1>&2
         exit 1
     }
-    (cd sut && GIT_SSH_COMMAND="${GIT_SSH}" git checkout "$gittag") || {
+    (cd sut && GIT_SSH_COMMAND="${GIT_SSH}" git checkout "$gittag" 1>/dev/null 2>/dev/null) || {
         echo "Error: Failed to checkout tag '$gittag' in repository '${giturl}'." 1>&2
         exit 1
     }
-    echo "$version_ordinal" > "./sut.version"  # readable by tests
+    echo "$ordinal" > "./sut.version"  # readable by tests
 
     # run tests
-    res=
-    if [[ $ordinal -le ${version_ordinal} ]]; then
-        # (todo: test older/stabler versions on firefox)
-        res=$(npx nightwatch --env="chrome" --src=tests --git-tag="$ft_version" --index="$index")
-    else
-        # test latest versions on chrome
-        res=$(npx nightwatch --env="chrome" --src=tests --git-tag="$ft_version" --index="$index")
-    fi
-    passed=$(echo "$res" | grep -oP "Tests passed: \K\d+" || echo "0")
-    failed=$(echo "$res" | grep -oP "Tests failed: \K\d+" || echo "0")
-    errors=$(echo "$res" | grep -oP "Errors: \K\d+" || echo "0")
-    skipped=$(echo "$res" | grep -oP "Skipped: \K\d+" || echo "0")
-    # defaults
-    : ${passed:=0}
-    : ${failed:=0}
-    : ${errors:=0}
-    : ${skipped:=0}
-
-    echo "${ft_version},$passed,$failed,$errors,$skipped" >> "$result_file"
-
+    ft_index=${index}
+    for t in ${src_dir}/act.svg/tests/test*
+    do
+        if [[ "$t" =~ '~' ]]; then
+            continue
+        fi
+        . ns run "$t"
+    done
+    . ns delete ft_index
+    # res=
+    # if [[ $ordinal -le ${version_ordinal} ]]; then
+    #     # (todo: test older/stabler versions on firefox)
+    #     res=$(npx nightwatch --env="chrome" --src=tests --git-tag="$ft_version" --index="$index")
+    # else
+    #     # test latest versions on chrome
+    #     res=$(npx nightwatch --env="chrome" --src=tests --git-tag="$ft_version" --index="$index")
+    # fi
+    # passed=$(echo "$res" | grep -oP "Tests passed: \K\d+" || echo "0")
+    # failed=$(echo "$res" | grep -oP "Tests failed: \K\d+" || echo "0")
+    # errors=$(echo "$res" | grep -oP "Errors: \K\d+" || echo "0")
+    # skipped=$(echo "$res" | grep -oP "Skipped: \K\d+" || echo "0")
+    # # defaults
+    # : ${passed:=0}
+    # : ${failed:=0}
+    # : ${errors:=0}
+    # : ${skipped:=0}
+    # echo "${ft_version},$passed,$failed,$errors,$skipped" >> "$result_file"
 done < "./versions.csv"
+
+read -p "Test run has ended. Press enter to quit the session..." _
+curl -s -X DELETE http://localhost:4444/session/${sel_sid} 1>/dev/null 2>/dev/null
+sleep 1
